Description:  Template para instancias.

Resources:
  NetworkStack: 
    Type: AWS::CloudFormation::Stack
    Properties: 
      TemplateURL: "https://trambo-elmer.s3-us-west-2.amazonaws.com/CloudFormation/Network/network.yml"
    
  BDStack: 
    Type: AWS::CloudFormation::Stack
    Properties: 
      TemplateURL: "https://trambo-elmer.s3-us-west-2.amazonaws.com/CloudFormation/BaseDatos/bd.yml"
      Parameters:
          RefSubnetsPrivadas: !GetAtt NetworkStack.Outputs.RefSubnetsPrivadas
          RefSG : !GetAtt NetworkStack.Outputs.RefSGBD
          RefDefaultSG : !GetAtt NetworkStack.Outputs.RefDefaultSG

  WordpressStack: 
    Type: AWS::CloudFormation::Stack
    Properties: 
      TemplateURL: "https://trambo-elmer.s3-us-west-2.amazonaws.com/CloudFormation/Instancias/wordpress.yml"
      Parameters:
          RefSubnetPublica: !GetAtt NetworkStack.Outputs.RefSubnetPublic1
          RefSG : !GetAtt NetworkStack.Outputs.RefSG
          EndpointBD: !GetAtt BDStack.Outputs.EndpointBD
          RefDefaultSG : !GetAtt NetworkStack.Outputs.RefDefaultSG